### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by mtucker502** [ansible-network/ansible_collections.juniper.junos#30]
##### SUMMARY

I installed the master branch into /Users/matucker/.ansible/collections/ansible_collections/juniper/junos

##### ISSUE TYPE

- Bug Report

##### ANSIBLE VERSION

```bash
$ ansible --version
ansible 2.9.0rc1
  config file = /Users/matucker/Downloads/junos_collection_test/ansible.cfg
  configured module search path = ['/Users/matucker/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/matucker/Downloads/junos_collection_test/venv/lib/python3.7/site-packages/ansible
  executable location = /Users/matucker/Downloads/junos_collection_test/venv/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

##### CONFIGURATION

```bash
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/Users/matucker/Downloads/junos_collection_test/ansible.cfg) = ['/Users/matucker/Downloads/junos_collection_test/hosts']
HOST_KEY_CHECKING(/Users/matucker/Downloads/junos_collection_test/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```bash
lab@alpsgagipxfw02-node0> show version
node0:
--------------------------------------------------------------------------
Hostname: lavender
Model: srx5800
Junos: 15.1X49-D180.2
AI-Scripts [6.0R1.1]
JUNOS Software Release [15.1X49-D180.2]
```

##### STEPS TO REPRODUCE

```bash
pip install --upgrade ansible==2.9.0rc1git clone https://github.com/ansible-network/ansible_collections.juniper.junos /Users/matucker/.ansible/collections/ansible_collections/juniper/junos
```

Inventory:

```ini
[junos]
lavender.ultralab.juniper.net

[junos:vars]
ansible_connection=netconf
ansible_network_os=junos
ansible_user=labroot
ansible_password=lab123
```

Playbook:

```yaml
---
- name: Playbook Test
  hosts: junos
  gather_facts: no

  tasks:
    - name: collections test
      juniper.junos.junos_facts:
```

##### ACTUAL RESULTS

```bash
$ ansible-playbook playbook.yml

PLAY [Playbook Test] **************************************************************************************************************************************************

TASK [collections test] ***********************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'module' object is not callable
[WARNING]: Platform darwin on host lavender.ultralab.juniper.net is using the discovered Python interpreter at /usr/bin/python, but future installation of another
Python interpreter could change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

fatal: [lavender.ultralab.juniper.net]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/matucker/.ansible/tmp/ansible-local-8901652lx8sg_/ansible-tmp-1569953794.1523468-146576032830703/AnsiballZ_junos_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/matucker/.ansible/tmp/ansible-local-8901652lx8sg_/ansible-tmp-1569953794.1523468-146576032830703/AnsiballZ_junos_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/matucker/.ansible/tmp/ansible-local-8901652lx8sg_/ansible-tmp-1569953794.1523468-146576032830703/AnsiballZ_junos_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.juniper.junos.plugins.modules.junos_facts', init_globals=None, run_name='__main__', alter_sys=False)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 180, in run_module\n    fname, loader, pkg_name)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/var/folders/04/g24gg21176zflhxqzl_82y9c0000gn/T/ansible_juniper.junos.junos_facts_payload_ccrKos/ansible_juniper.junos.junos_facts_payload.zip/ansible_collections/juniper/junos/plugins/modules/junos_facts.py\", line 147, in <module>\n  File \"/var/folders/04/g24gg21176zflhxqzl_82y9c0000gn/T/ansible_juniper.junos.junos_facts_payload_ccrKos/ansible_juniper.junos.junos_facts_payload.zip/ansible_collections/juniper/junos/plugins/modules/junos_facts.py\", line 138, in main\nTypeError: 'module' object is not callable\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP ************************************************************************************************************************************************************
lavender.ultralab.juniper.net : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

(venv) matucker-mbp:junos_collection_test matucker$ ansible-playbook playbook.yml -vvv
ansible-playbook 2.9.0rc1
  config file = /Users/matucker/Downloads/junos_collection_test/ansible.cfg
  configured module search path = ['/Users/matucker/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/matucker/Downloads/junos_collection_test/venv/lib/python3.7/site-packages/ansible
  executable location = /Users/matucker/Downloads/junos_collection_test/venv/bin/ansible-playbook
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
Using /Users/matucker/Downloads/junos_collection_test/ansible.cfg as config file
host_list declined parsing /Users/matucker/Downloads/junos_collection_test/hosts as it did not pass its verify_file() method
script declined parsing /Users/matucker/Downloads/junos_collection_test/hosts as it did not pass its verify_file() method
auto declined parsing /Users/matucker/Downloads/junos_collection_test/hosts as it did not pass its verify_file() method
Parsed /Users/matucker/Downloads/junos_collection_test/hosts inventory source with ini plugin

PLAYBOOK: playbook.yml ************************************************************************************************************************************************
1 plays in playbook.yml

PLAY [Playbook Test] **************************************************************************************************************************************************
META: ran handlers

TASK [collections test] ***********************************************************************************************************************************************
task path: /Users/matucker/Downloads/junos_collection_test/playbook.yml:10
<lavender.ultralab.juniper.net> ESTABLISH LOCAL CONNECTION FOR USER: matucker
<lavender.ultralab.juniper.net> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/matucker/.ansible/tmp/ansible-local-890424f0si5xv/ansible-tmp-1569953802.2318-94715111093488 `" && echo ansible-tmp-1569953802.2318-94715111093488="` echo /Users/matucker/.ansible/tmp/ansible-local-890424f0si5xv/ansible-tmp-1569953802.2318-94715111093488 `" ) && sleep 0'
<lavender.ultralab.juniper.net> Attempting python interpreter discovery
<lavender.ultralab.juniper.net> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<lavender.ultralab.juniper.net> Python interpreter discovery fallback (unsupported platform for extended discovery: darwin)
Using module file /Users/matucker/.ansible/collections/ansible_collections/juniper/junos/plugins/modules/junos_facts.py
<lavender.ultralab.juniper.net> PUT /Users/matucker/.ansible/tmp/ansible-local-890424f0si5xv/tmp0dfzt56z TO /Users/matucker/.ansible/tmp/ansible-local-890424f0si5xv/ansible-tmp-1569953802.2318-94715111093488/AnsiballZ_junos_facts.py
<lavender.ultralab.juniper.net> EXEC /bin/sh -c 'chmod u+x /Users/matucker/.ansible/tmp/ansible-local-890424f0si5xv/ansible-tmp-1569953802.2318-94715111093488/ /Users/matucker/.ansible/tmp/ansible-local-890424f0si5xv/ansible-tmp-1569953802.2318-94715111093488/AnsiballZ_junos_facts.py && sleep 0'
<lavender.ultralab.juniper.net> EXEC /bin/sh -c '/usr/bin/python /Users/matucker/.ansible/tmp/ansible-local-890424f0si5xv/ansible-tmp-1569953802.2318-94715111093488/AnsiballZ_junos_facts.py && sleep 0'
<lavender.ultralab.juniper.net> EXEC /bin/sh -c 'rm -f -r /Users/matucker/.ansible/tmp/ansible-local-890424f0si5xv/ansible-tmp-1569953802.2318-94715111093488/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/Users/matucker/.ansible/tmp/ansible-local-890424f0si5xv/ansible-tmp-1569953802.2318-94715111093488/AnsiballZ_junos_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/matucker/.ansible/tmp/ansible-local-890424f0si5xv/ansible-tmp-1569953802.2318-94715111093488/AnsiballZ_junos_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/matucker/.ansible/tmp/ansible-local-890424f0si5xv/ansible-tmp-1569953802.2318-94715111093488/AnsiballZ_junos_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.juniper.junos.plugins.modules.junos_facts', init_globals=None, run_name='__main__', alter_sys=False)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/var/folders/04/g24gg21176zflhxqzl_82y9c0000gn/T/ansible_juniper.junos.junos_facts_payload_obny4v/ansible_juniper.junos.junos_facts_payload.zip/ansible_collections/juniper/junos/plugins/modules/junos_facts.py", line 147, in <module>
  File "/var/folders/04/g24gg21176zflhxqzl_82y9c0000gn/T/ansible_juniper.junos.junos_facts_payload_obny4v/ansible_juniper.junos.junos_facts_payload.zip/ansible_collections/juniper/junos/plugins/modules/junos_facts.py", line 138, in main
TypeError: 'module' object is not callable

[WARNING]: Platform darwin on host lavender.ultralab.juniper.net is using the discovered Python interpreter at /usr/bin/python, but future installation of another
Python interpreter could change this. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.

fatal: [lavender.ultralab.juniper.net]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/matucker/.ansible/tmp/ansible-local-890424f0si5xv/ansible-tmp-1569953802.2318-94715111093488/AnsiballZ_junos_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/matucker/.ansible/tmp/ansible-local-890424f0si5xv/ansible-tmp-1569953802.2318-94715111093488/AnsiballZ_junos_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/matucker/.ansible/tmp/ansible-local-890424f0si5xv/ansible-tmp-1569953802.2318-94715111093488/AnsiballZ_junos_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.juniper.junos.plugins.modules.junos_facts', init_globals=None, run_name='__main__', alter_sys=False)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 180, in run_module\n    fname, loader, pkg_name)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/var/folders/04/g24gg21176zflhxqzl_82y9c0000gn/T/ansible_juniper.junos.junos_facts_payload_obny4v/ansible_juniper.junos.junos_facts_payload.zip/ansible_collections/juniper/junos/plugins/modules/junos_facts.py\", line 147, in <module>\n  File \"/var/folders/04/g24gg21176zflhxqzl_82y9c0000gn/T/ansible_juniper.junos.junos_facts_payload_obny4v/ansible_juniper.junos.junos_facts_payload.zip/ansible_collections/juniper/junos/plugins/modules/junos_facts.py\", line 138, in main\nTypeError: 'module' object is not callable\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP ************************************************************************************************************************************************************
lavender.ultralab.juniper.net : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by mtucker502** [comment]
I tried this same setup on Ubuntu 16.04.5 LTS and it works. This is specific to MacOS
